import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import './globals.css'
import Navbar from '@/components/Navbar.jsx'
import { Toaster } from 'sonner'
// import AsyncNavbar from '@/components/asyncNavbar'

export const metadata = {
  title: 'Silent Talk - ASL Learning',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          {/* Header */}
          <header className="flex justify-end items-center p-4 gap-4 h-16 bg-white shadow-md flex-shrink-0">
            <SignedOut>
              <SignInButton />
              <SignUpButton>
                <button className="bg-[#6c47ff] text-ceramic-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              { "Navbar"}
              {/* <AsyncNavbar /> */}
              <Navbar />
              <UserButton />
            </SignedIn>
          </header>

          {/* Scrollable main content */}
          <main className="min-h-screen">
            <Toaster position='top-right'/>
            {children}
          </main>

          {/* Footer */}
          <footer className="p-4 text-center text-sm text-gray-500 flex-shrink-0 bg-white shadow-inner">
            &copy; {new Date().getFullYear()} Silent Talk. All rights reserved.
          </footer>
        </body>
      </html>
    </ClerkProvider>
  )
}
